# Generated by Django 6.0.4 on 2026-04-20 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='İçerik')),
                ('priority', models.IntegerField(choices=[(1, 'Düşük'), (2, 'Orta'), (3, 'Yüksek')], default=2, verbose_name='Öncelik')),
                ('is_active', models.BooleanField(default=True, help_text='İşaretsiz duyurular API ve sitede gösterilmez.', verbose_name='Aktif mi?')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Otomatik oluşturulan evrensel benzersiz tanımlayıcı.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, help_text="URL'de kullanılacak kısa etiket. Boş bırakılırsa başlıktan üretilir.", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Konum')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizatör')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_number', models.CharField(help_text='Üniversite öğrenci numarası.', max_length=20, unique=True, verbose_name='Öğrenci Numarası')),
                ('role', models.CharField(choices=[('member', 'Üye'), ('board', 'Yönetim Kurulu'), ('admin', 'Yönetici')], default='member', max_length=20, verbose_name='Rol')),
                ('bio', models.TextField(blank=True, verbose_name='Hakkında')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil Fotoğrafı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
