# Generated by Django 5.2.8 on 2026-04-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board/', verbose_name='Fotoğraf')),
                ('title', models.CharField(max_length=150, verbose_name='Unvan')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Yönetim Kurulu Üyesi',
                'verbose_name_plural': 'Yönetim Kurulu Üyeleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Firma Adı')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='Firma Logosu')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Web Sitesi Linki')),
                ('order', models.IntegerField(default=0, verbose_name='Görüntülenme Sırası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsorlar',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/', verbose_name='Kapak Fotoğrafı'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Koordinatörlük Adı')),
                ('description', models.CharField(max_length=250, verbose_name='Kısa Açıklama')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='departments/', verbose_name='Logo/İkon')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.boardmember', verbose_name='Koordinatörlük Başkanı')),
            ],
            options={
                'verbose_name': 'Koordinatörlük',
                'verbose_name_plural': 'Koordinatörlükler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='event_photos/', verbose_name='Fotoğraf')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.event', verbose_name='Etkinlik')),
            ],
            options={
                'verbose_name': 'Etkinlik Fotoğrafı',
                'verbose_name_plural': 'Etkinlik Fotoğrafları',
                'ordering': ['-created_at'],
            },
        ),
    ]
