# Generated by Django 6.0.5 on 2026-05-18 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boardmember_sponsor_event_cover_image_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimMesaji',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('subject', models.CharField(max_length=255, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj İçeriği')),
                ('is_read', models.BooleanField(default=False, help_text='Yönetici tarafından okunup okunmadığını gösterir.', verbose_name='Okundu mu?')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UyeBasvurusu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon Numarası')),
                ('student_number', models.CharField(max_length=20, verbose_name='Öğrenci Numarası')),
                ('department', models.CharField(help_text='Başvuranın üniversitedeki bölümü.', max_length=150, verbose_name='Bölüm')),
                ('motivation', models.TextField(blank=True, help_text='Neden bu kulübe katılmak istiyorsunuz?', verbose_name='Motivasyon Yazısı')),
                ('status', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20, verbose_name='Başvuru Durumu')),
            ],
            options={
                'verbose_name': 'Üyelik Başvurusu',
                'verbose_name_plural': 'Üyelik Başvuruları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etkinlik Tarihi ve Saati'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Konum'),
        ),
    ]
