# Generated by Django 6.0.5 on 2026-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_iletisimmesaji_uyebasvurusu'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etkinlik Tarihi ve Saati'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Konum'),
        ),
    ]
