"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env dosyasını projenin kök dizininden (manage.py ile aynı seviye) yükle
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Yerelde .env içinde DEBUG=True verilir; Render'da tanımlanmazsa False olur.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Render'da SECRET_KEY ortam değişkeni tanımlanmalı.
# Rastgele yedek anahtar yalnızca DEBUG modunda kullanılır: production'da her
# worker farklı anahtar üretirse oturum/CSRF doğrulamaları bozulur.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured("SECRET_KEY ortam değişkeni tanımlanmalı.")
    SECRET_KEY = get_random_secret_key()

# Render'da ALLOWED_HOSTS="servis-adi.onrender.com" (virgülle birden fazla) verilir.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Render bu değişkeni otomatik tanımlar (ör. servis-adi.onrender.com)
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Render HTTPS'i proxy'de sonlandırır; Django'nun isteği HTTPS olarak tanıması için gerekli
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production'da çerezler yalnızca HTTPS üzerinden gönderilsin (yerelde HTTP için DEBUG'da kapalı)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# HTTPS üzerinden admin/oturum POST'ları için (ör. "https://servis-adi.onrender.com")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    # Django yerleşik uygulamaları
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Üçüncü taraf
    "rest_framework",        # pip install djangorestframework
    "django_filters",        # pip install django-filter
    "corsheaders",           # pip install django-cors-headers

    # Kendi uygulamalarımız
    "core",

    #Cloudflare r2
    "storages",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',     # Statik dosyaları sunar — SecurityMiddleware'den hemen sonra
    'corsheaders.middleware.CorsMiddleware',          # CORS — CommonMiddleware'den ÖNCE olmalı
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # collectstatic çıktısı; WhiteNoise buradan sunar


# ---------------------------------------------------------------------------
# CORS ayarları (Frontend erişimi için)
# ---------------------------------------------------------------------------
# Virgülle ayrılmış liste, ör: "https://frontend.com,http://localhost:5173"
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]

# Credential (cookie, auth header) gönderimini destekle
CORS_ALLOW_CREDENTIALS = True


# ---------------------------------------------------------------------------
# DRF genel ayarları
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    # Varsayılan kimlik doğrulama yöntemleri
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",  # Tarayıcı / admin
        "rest_framework.authentication.BasicAuthentication",    # Geliştirme/test
        # Üretimde JWT için: "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],

    # Varsayılan izin politikası
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],

    # Yanıt formatı: yalnızca JSON (Browsable API production'da kapatılır)
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        # Geliştirmede şunu da ekleyebilirsiniz:
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],

    # Varsayılan filtreleme backend'i
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],

    # Sayfalama: her sayfada en fazla 20 kayıt
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,

    # Tarih/saat formatı (ISO 8601 — JavaScript ile uyumlu)
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%SZ",
}

# ---------------------------------------------------------------------------
# Medya dosyaları (profil fotoğrafları için)
# ---------------------------------------------------------------------------
MEDIA_URL  = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CLOUDFLARE R2 DEPOLAMA AYARLARI ---
AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = f"https://{os.getenv('R2_ACCOUNT_ID')}.eu.r2.cloudflarestorage.com"
AWS_S3_REGION_NAME = 'auto'
AWS_S3_SIGNATURE_VERSION = 's3v4'                # R2 için gerekli imza sürümü
AWS_QUERYSTRING_AUTH = False                      # Dosya URL'lerinde imza parametresi olmasın
# Dosya URL'leri için public domain — şema olmadan, ör: "pub-xxxx.r2.dev" veya "cdn.ornek.com".
# django-storages URL'yi https://<domain>/<dosya> olarak üretir. Yükleme yine
# AWS_S3_ENDPOINT_URL üzerinden yapılır; bu ayar yalnızca okuma URL'lerini etkiler.
AWS_S3_CUSTOM_DOMAIN = os.environ.get('R2_CUSTOM_DOMAIN') or None

# Django 6.0 için modern depolama ayarı (DEFAULT_FILE_STORAGE artık deprecated)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        # Statik dosyalar yerel kalır; WhiteNoise sıkıştırır ve hash'li isimle önbelleğe uygun sunar
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}