"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env dosyasını projenin kök dizininden (manage.py ile aynı seviye) yükle
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h-!b_t36^f+&rmcb3vvc8(3y$5j1)5c6*c5w&syvwv-wiaxewl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django yerleşik uygulamaları
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Üçüncü taraf
    "rest_framework",        # pip install djangorestframework
    "django_filters",        # pip install django-filter
    "corsheaders",           # pip install django-cors-headers

    # Kendi uygulamalarımız
    "core",

    #Cloudflare r2
    "storages",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',          # CORS — CommonMiddleware'den ÖNCE olmalı
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ---------------------------------------------------------------------------
# CORS ayarları (Frontend erişimi için)
# ---------------------------------------------------------------------------
# Geliştirme ortamında tüm origin'lere izin ver
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Yalnızca DEBUG=True iken tümüne açık

# Production'da aşağıdaki listeyi kullanın (CORS_ALLOW_ALL_ORIGINS = False yapın):
# CORS_ALLOWED_ORIGINS = [
#     "https://sizin-frontend-domaininiz.com",
#     "http://localhost:3000",
#     "http://localhost:5173",
# ]

# Credential (cookie, auth header) gönderimini destekle
CORS_ALLOW_CREDENTIALS = True


# ---------------------------------------------------------------------------
# DRF genel ayarları
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    # Varsayılan kimlik doğrulama yöntemleri
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",  # Tarayıcı / admin
        "rest_framework.authentication.BasicAuthentication",    # Geliştirme/test
        # Üretimde JWT için: "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],

    # Varsayılan izin politikası
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],

    # Yanıt formatı: yalnızca JSON (Browsable API production'da kapatılır)
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        # Geliştirmede şunu da ekleyebilirsiniz:
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],

    # Varsayılan filtreleme backend'i
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],

    # Sayfalama: her sayfada en fazla 20 kayıt
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,

    # Tarih/saat formatı (ISO 8601 — JavaScript ile uyumlu)
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%SZ",
}

# ---------------------------------------------------------------------------
# Medya dosyaları (profil fotoğrafları için)
# ---------------------------------------------------------------------------
MEDIA_URL  = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CLOUDFLARE R2 DEPOLAMA AYARLARI ---
AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = f"https://{os.getenv('R2_ACCOUNT_ID')}.r2.cloudflarestorage.com"
AWS_S3_REGION_NAME = 'auto'

# Django'ya "Dosyaları artık R2'ye fırlat" diyoruz
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'